; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:upesy_wroom]
platform = espressif32
;board = alksesp32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
lib_deps = 
	arduino-libraries/NTPClient@^3.2.1
	crankyoldgit/IRremoteESP8266@2.9.0
	paulstoffregen/Encoder@^1.4.4
	mathertel/RotaryEncoder@^1.5.3
	madhephaestus/ESP32Encoder@^0.11.7
	smougenot/TM1637@0.0.0-alpha+sha.9486982048
board_build.partitions = huge_app.csv
build_flags = -std=gnu++11

